name: 'de_projects'
config-version: 2
version: '1.0.0'
profile: 'default'

model-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

vars:
  copy_into_settings:
    walmart:
      target_schema: walmart_db.bronze
      stage: walmart_db.bronze.walmart_s3_stage
      file_format: walmart_db.bronze.csv_format
      force: TRUE

models:
  de_projects:
    walmart:
      +database: walmart_db
      bronze:
        +schema: bronze
        +materialized: view
      silver:
        +schema: silver
        +materialized: table
      gold:
        +schema: gold
        +materialized: view


