name: 'de_projects'
config-version: 2
version: '1.0.0'

profile: 'default'

model-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # stores compiled SQL files
clean-targets:         # removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  copy_into_config:
    walmart:
      target_schema: walmart_db.bronze
      from_stage: walmart_db.bronze.walmart_s3_stage
      file_format: walmart_db.bronze.csv_format
      force: TRUE

models:
  de_projects:
    walmart:
      +database: walmart_db
      bronze:
        +schema: bronze
        +materialized: table
      silver:
        +schema: silver
        +materialized: table
      gold:
        +schema: gold
        +materialized: table


