name: 'dea_projects'
config-version: 2
version: '1.0.0'

profile: 'default'

model-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # stores compiled SQL files
clean-targets:         # removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dea_projects:
    walmart:
      +database: walmart_db
      bronze:
        +schema: bronze
        +materialized: view


